#!/bin/sh

machine=mini2440
user=

# use 'dhcp' to do dhcp in barebox and in kernel
# use 'none' if you want to skip kernel ip autoconfiguration
ip=dhcp

# or set your networking parameters here
#eth0.ipaddr=a.b.c.d
#eth0.netmask=a.b.c.d
#eth0.gateway=a.b.c.d
#eth0.serverip=a.b.c.d
#eth0.ethaddr=a:b:b:d:e:f

# can be either 'net', 'nand' or 'mmc'
kernel_loc=nand
# can be either 'net', 'nand', 'initrd' or 'mmc'
rootfs_loc=nand

# can be either 'jffs2' or 'ubifs' for flash or 'ext3' for mmc
rootfs_type=jffs2
rootfsimage=root-${machine}.${rootfs_type}

# The image type of the kernel. Can be uimage, zimage, raw, or raw_lzo
#kernelimage_type=zimage
#kernelimage=zImage-${machine}
kernelimage_type=uimage
kernelimage=uImage-$machine
#kernelimage_type=raw
#kernelimage=Image-$machine
#kernelimage_type=raw_lzo
#kernelimage=Image-$machine.lzo

# the name of the barebox image used by the update script
bareboximage=barebox-$machine

# the name of the barebox default environment used by the update script
bareboxenvimage=barebox-default-environment-$machine

if [ -n $user ]; then
	kernelimage="${user}"-"${kernelimage}"
	nfsroot="${eth0.serverip}:/home/${user}/nfsroot/${machine}"
	rootfsimage="${user}"-"${rootfsimage}"
else
	nfsroot="${eth0.serverip}:/path/to/nfs/root"
fi

autoboot_timeout=3

#
# "mini2440" kernel parameter
# 0 .. 9 = screen type
# b = backlight enabled
# t = touch enabled
# c = camera enabled
# Note: can be "mini2440= " if nothing of these components are connected
#
bootargs="console=ttySAC0,115200 mini2440=0tbc"

# TODO NOR support

nand_device="nand"
nand_parts="512k(barebox),384k(bareboxenv),2048k(kernel),-(root)"

# rootfs's partition number if rootfs_loc == nand
rootfs_mtdblock_nand=3

# kernel's partition number, if kernel_loc == mmc
# (starting with # 0)
kernel_mmc_part=0

# rootfs's partition number if rootfs_loc == mmc
# (starting with # 1)
rootfs_mmc_part=2
